In [1]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
folder1=r"Final Positive Dataset\Upstairs"
folder2=r"Final Positive Dataset\Downstairs"
folder3=r"Final Negative Dataset"

In [3]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('Positive_Up.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (121, 128)
descriptor shape  1  :  (193, 128)
descriptor shape  2  :  (119, 128)
descriptor shape  3  :  (66, 128)
descriptor shape  4  :  (207, 128)
descriptor shape  5  :  (87, 128)
descriptor shape  6  :  (370, 128)
descriptor shape  7  :  (195, 128)
descriptor shape  8  :  (288, 128)
descriptor shape  9  :  (282, 128)
descriptor shape  10  :  (135, 128)
descriptor shape  11  :  (129, 128)
descriptor shape  12  :  (55, 128)
descriptor shape  13  :  (62, 128)
descriptor shape  14  :  (213, 128)
descriptor shape  15  :  (227, 128)
descriptor shape  16  :  (262, 128)
descriptor shape  17  :  (193, 128)
descriptor shape  18  :  (103, 128)
descriptor shape  19  :  (328, 128)
descriptor shape  20  :  (282, 128)
descriptor shape  21  :  (222, 128)
descriptor shape  22  :  (151, 128)
descriptor shape  23  :  (122, 128)
descriptor shape  24  :  (155, 128)
descriptor shape  25  :  (76, 128)
descriptor shape  26  :  (77, 128)
descriptor shape  27  :  (150, 128)
descript

descriptor shape  228  :  (81, 128)
descriptor shape  229  :  (380, 128)
descriptor shape  230  :  (151, 128)
descriptor shape  231  :  (280, 128)
descriptor shape  232  :  (185, 128)
descriptor shape  233  :  (310, 128)
descriptor shape  234  :  (78, 128)
descriptor shape  235  :  (239, 128)
descriptor shape  236  :  (324, 128)
descriptor shape  237  :  (131, 128)
descriptor shape  238  :  (163, 128)
descriptor shape  239  :  (410, 128)
descriptor shape  240  :  (74, 128)
descriptor shape  241  :  (503, 128)
descriptor shape  242  :  (234, 128)
descriptor shape  243  :  (380, 128)
descriptor shape  244  :  (363, 128)
descriptor shape  245  :  (86, 128)
descriptor shape  246  :  (256, 128)
descriptor shape  247  :  (331, 128)
descriptor shape  248  :  (87, 128)
descriptor shape  249  :  (58, 128)
descriptor shape  250  :  (267, 128)
descriptor shape  251  :  (121, 128)
descriptor shape  252  :  (139, 128)
descriptor shape  253  :  (381, 128)
descriptor shape  254  :  (78, 128)
descript

descriptor shape  453  :  (94, 128)
descriptor shape  454  :  (513, 128)
descriptor shape  455  :  (410, 128)
descriptor shape  456  :  (88, 128)
descriptor shape  457  :  (127, 128)
descriptor shape  458  :  (352, 128)
descriptor shape  459  :  (191, 128)
descriptor shape  460  :  (341, 128)
descriptor shape  461  :  (118, 128)
descriptor shape  462  :  (119, 128)
descriptor shape  463  :  (319, 128)
descriptor shape  464  :  (86, 128)
descriptor shape  465  :  (87, 128)
descriptor shape  466  :  (78, 128)
descriptor shape  467  :  (289, 128)
descriptor shape  468  :  (156, 128)
descriptor shape  469  :  (51, 128)
descriptor shape  470  :  (287, 128)
descriptor shape  471  :  (293, 128)
descriptor shape  472  :  (230, 128)
descriptor shape  473  :  (436, 128)
descriptor shape  474  :  (71, 128)
descriptor shape  475  :  (74, 128)
descriptor shape  476  :  (174, 128)
descriptor shape  477  :  (139, 128)
descriptor shape  478  :  (182, 128)
descriptor shape  479  :  (102, 128)
descripto

descriptor shape  680  :  (83, 128)
descriptor shape  681  :  (174, 128)
descriptor shape  682  :  (594, 128)
descriptor shape  683  :  (193, 128)
descriptor shape  684  :  (216, 128)
descriptor shape  685  :  (143, 128)
descriptor shape  686  :  (105, 128)
descriptor shape  687  :  (59, 128)
descriptor shape  688  :  (341, 128)
descriptor shape  689  :  (370, 128)
descriptor shape  690  :  (265, 128)
descriptor shape  691  :  (118, 128)
descriptor shape  692  :  (585, 128)
descriptor shape  693  :  (417, 128)
descriptor shape  694  :  (399, 128)
descriptor shape  695  :  (77, 128)
descriptor shape  696  :  (86, 128)
descriptor shape  697  :  (211, 128)
descriptor shape  698  :  (121, 128)
descriptor shape  699  :  (91, 128)
descriptor shape  700  :  (86, 128)
descriptor shape  701  :  (300, 128)
descriptor shape  702  :  (120, 128)
descriptor shape  703  :  (119, 128)
descriptor shape  704  :  (347, 128)
descriptor shape  705  :  (244, 128)
descriptor shape  706  :  (72, 128)
descript

descriptor shape  903  :  (177, 128)
descriptor shape  904  :  (167, 128)
descriptor shape  905  :  (80, 128)
descriptor shape  906  :  (348, 128)
descriptor shape  907  :  (394, 128)
descriptor shape  908  :  (476, 128)
descriptor shape  909  :  (85, 128)
descriptor shape  910  :  (31, 128)
descriptor shape  911  :  (180, 128)
descriptor shape  912  :  (195, 128)
descriptor shape  913  :  (720, 128)
descriptor shape  914  :  (380, 128)
descriptor shape  915  :  (174, 128)
descriptor shape  916  :  (133, 128)
descriptor shape  917  :  (347, 128)
descriptor shape  918  :  (67, 128)
descriptor shape  919  :  (166, 128)
descriptor shape  920  :  (154, 128)
descriptor shape  921  :  (273, 128)
descriptor shape  922  :  (339, 128)
descriptor shape  923  :  (258, 128)
descriptor shape  924  :  (282, 128)
descriptor shape  925  :  (352, 128)
descriptor shape  926  :  (331, 128)
descriptor shape  927  :  (248, 128)
descriptor shape  928  :  (213, 128)
descriptor shape  929  :  (301, 128)
descr

descriptor shape  1125  :  (352, 128)
descriptor shape  1126  :  (121, 128)
descriptor shape  1127  :  (68, 128)
descriptor shape  1128  :  (203, 128)
descriptor shape  1129  :  (90, 128)
descriptor shape  1130  :  (44, 128)
descriptor shape  1131  :  (349, 128)
descriptor shape  1132  :  (71, 128)
descriptor shape  1133  :  (488, 128)
descriptor shape  1134  :  (88, 128)
descriptor shape  1135  :  (59, 128)
descriptor shape  1136  :  (177, 128)
descriptor shape  1137  :  (356, 128)
descriptor shape  1138  :  (394, 128)
descriptor shape  1139  :  (87, 128)
descriptor shape  1140  :  (349, 128)
descriptor shape  1141  :  (81, 128)
descriptor shape  1142  :  (258, 128)
descriptor shape  1143  :  (374, 128)
descriptor shape  1144  :  (156, 128)
descriptor shape  1145  :  (258, 128)
descriptor shape  1146  :  (162, 128)
descriptor shape  1147  :  (138, 128)
descriptor shape  1148  :  (127, 128)
descriptor shape  1149  :  (394, 128)
descriptor shape  1150  :  (101, 128)
descriptor shape  11

descriptor shape  1348  :  (219, 128)
descriptor shape  1349  :  (127, 128)
descriptor shape  1350  :  (503, 128)
descriptor shape  1351  :  (264, 128)
descriptor shape  1352  :  (125, 128)
descriptor shape  1353  :  (380, 128)
descriptor shape  1354  :  (215, 128)
descriptor shape  1355  :  (83, 128)
descriptor shape  1356  :  (80, 128)
descriptor shape  1357  :  (94, 128)
descriptor shape  1358  :  (356, 128)
descriptor shape  1359  :  (211, 128)
descriptor shape  1360  :  (119, 128)
descriptor shape  1361  :  (68, 128)
descriptor shape  1362  :  (168, 128)
descriptor shape  1363  :  (209, 128)
descriptor shape  1364  :  (118, 128)
descriptor shape  1365  :  (78, 128)
descriptor shape  1366  :  (193, 128)
descriptor shape  1367  :  (145, 128)
descriptor shape  1368  :  (119, 128)
descriptor shape  1369  :  (172, 128)
descriptor shape  1370  :  (184, 128)
descriptor shape  1371  :  (87, 128)
descriptor shape  1372  :  (191, 128)
descriptor shape  1373  :  (125, 128)
descriptor shape  

descriptor shape  1569  :  (131, 128)
descriptor shape  1570  :  (248, 128)
descriptor shape  1571  :  (183, 128)
descriptor shape  1572  :  (80, 128)
descriptor shape  1573  :  (248, 128)
descriptor shape  1574  :  (182, 128)
descriptor shape  1575  :  (197, 128)
descriptor shape  1576  :  (189, 128)
descriptor shape  1577  :  (158, 128)
descriptor shape  1578  :  (230, 128)
descriptor shape  1579  :  (188, 128)
descriptor shape  1580  :  (48, 128)
descriptor shape  1581  :  (493, 128)
descriptor shape  1582  :  (34, 128)
descriptor shape  1583  :  (355, 128)
descriptor shape  1584  :  (112, 128)
descriptor shape  1585  :  (78, 128)
descriptor shape  1586  :  (72, 128)
descriptor shape  1587  :  (90, 128)
descriptor shape  1588  :  (138, 128)
descriptor shape  1589  :  (78, 128)
descriptor shape  1590  :  (83, 128)
descriptor shape  1591  :  (214, 128)
descriptor shape  1592  :  (71, 128)
descriptor shape  1593  :  (176, 128)
descriptor shape  1594  :  (174, 128)
descriptor shape  159

descriptor shape  1790  :  (248, 128)
descriptor shape  1791  :  (239, 128)
descriptor shape  1792  :  (96, 128)
descriptor shape  1793  :  (63, 128)
descriptor shape  1794  :  (513, 128)
descriptor shape  1795  :  (222, 128)
descriptor shape  1796  :  (79, 128)
descriptor shape  1797  :  (92, 128)
descriptor shape  1798  :  (217, 128)
descriptor shape  1799  :  (188, 128)
descriptor shape  1800  :  (367, 128)
descriptor shape  1801  :  (122, 128)
descriptor shape  1802  :  (85, 128)
descriptor shape  1803  :  (380, 128)
descriptor shape  1804  :  (193, 128)
descriptor shape  1805  :  (217, 128)
descriptor shape  1806  :  (144, 128)
descriptor shape  1807  :  (258, 128)
descriptor shape  1808  :  (157, 128)
descriptor shape  1809  :  (57, 128)
descriptor shape  1810  :  (169, 128)
descriptor shape  1811  :  (90, 128)
descriptor shape  1812  :  (274, 128)
descriptor shape  1813  :  (162, 128)
descriptor shape  1814  :  (352, 128)
descriptor shape  1815  :  (44, 128)
descriptor shape  18

descriptor shape  2010  :  (54, 128)
descriptor shape  2011  :  (75, 128)
descriptor shape  2012  :  (141, 128)
descriptor shape  2013  :  (169, 128)
descriptor shape  2014  :  (172, 128)
descriptor shape  2015  :  (56, 128)
descriptor shape  2016  :  (65, 128)
descriptor shape  2017  :  (526, 128)
descriptor shape  2018  :  (252, 128)
descriptor shape  2019  :  (215, 128)
descriptor shape  2020  :  (356, 128)
descriptor shape  2021  :  (152, 128)
descriptor shape  2022  :  (217, 128)
descriptor shape  2023  :  (122, 128)
descriptor shape  2024  :  (250, 128)
descriptor shape  2025  :  (122, 128)
descriptor shape  2026  :  (85, 128)
descriptor shape  2027  :  (121, 128)
descriptor shape  2028  :  (65, 128)
descriptor shape  2029  :  (97, 128)
descriptor shape  2030  :  (61, 128)
descriptor shape  2031  :  (167, 128)
descriptor shape  2032  :  (174, 128)
descriptor shape  2033  :  (363, 128)
descriptor shape  2034  :  (227, 128)
descriptor shape  2035  :  (255, 128)
descriptor shape  20

descriptor shape  2230  :  (255, 128)
descriptor shape  2231  :  (65, 128)
descriptor shape  2232  :  (283, 128)
descriptor shape  2233  :  (74, 128)
descriptor shape  2234  :  (63, 128)
descriptor shape  2235  :  (53, 128)
descriptor shape  2236  :  (341, 128)
descriptor shape  2237  :  (462, 128)
descriptor shape  2238  :  (255, 128)
descriptor shape  2239  :  (199, 128)
descriptor shape  2240  :  (273, 128)
descriptor shape  2241  :  (526, 128)
descriptor shape  2242  :  (272, 128)
descriptor shape  2243  :  (123, 128)
descriptor shape  2244  :  (112, 128)
descriptor shape  2245  :  (83, 128)
descriptor shape  2246  :  (168, 128)
descriptor shape  2247  :  (181, 128)
descriptor shape  2248  :  (45, 128)
descriptor shape  2249  :  (74, 128)
descriptor shape  2250  :  (250, 128)
descriptor shape  2251  :  (73, 128)
descriptor shape  2252  :  (67, 128)
descriptor shape  2253  :  (156, 128)
descriptor shape  2254  :  (91, 128)
descriptor shape  2255  :  (152, 128)
descriptor shape  2256

descriptor shape  2451  :  (79, 128)
descriptor shape  2452  :  (66, 128)
descriptor shape  2453  :  (278, 128)
descriptor shape  2454  :  (107, 128)
descriptor shape  2455  :  (96, 128)
descriptor shape  2456  :  (91, 128)
descriptor shape  2457  :  (136, 128)
descriptor shape  2458  :  (155, 128)
descriptor shape  2459  :  (107, 128)
descriptor shape  2460  :  (244, 128)
descriptor shape  2461  :  (137, 128)
descriptor shape  2462  :  (380, 128)
descriptor shape  2463  :  (166, 128)
descriptor shape  2464  :  (211, 128)
descriptor shape  2465  :  (283, 128)
descriptor shape  2466  :  (489, 128)
descriptor shape  2467  :  (144, 128)
descriptor shape  2468  :  (78, 128)
descriptor shape  2469  :  (130, 128)
descriptor shape  2470  :  (71, 128)
descriptor shape  2471  :  (311, 128)
descriptor shape  2472  :  (232, 128)
descriptor shape  2473  :  (106, 128)
descriptor shape  2474  :  (225, 128)
descriptor shape  2475  :  (123, 128)
descriptor shape  2476  :  (154, 128)
descriptor shape  

descriptor shape  2672  :  (370, 128)
descriptor shape  2673  :  (237, 128)
descriptor shape  2674  :  (221, 128)
descriptor shape  2675  :  (301, 128)
descriptor shape  2676  :  (175, 128)
descriptor shape  2677  :  (131, 128)
descriptor shape  2678  :  (124, 128)
descriptor shape  2679  :  (94, 128)
descriptor shape  2680  :  (124, 128)
descriptor shape  2681  :  (229, 128)
descriptor shape  2682  :  (167, 128)
descriptor shape  2683  :  (116, 128)
descriptor shape  2684  :  (116, 128)
descriptor shape  2685  :  (55, 128)
descriptor shape  2686  :  (77, 128)
descriptor shape  2687  :  (164, 128)
descriptor shape  2688  :  (250, 128)
descriptor shape  2689  :  (122, 128)
descriptor shape  2690  :  (258, 128)
descriptor shape  2691  :  (38, 128)
descriptor shape  2692  :  (248, 128)
descriptor shape  2693  :  (84, 128)
descriptor shape  2694  :  (104, 128)
descriptor shape  2695  :  (169, 128)
descriptor shape  2696  :  (111, 128)
descriptor shape  2697  :  (66, 128)
descriptor shape  

descriptor shape  2897  :  (135, 128)
descriptor shape  2898  :  (80, 128)
descriptor shape  2899  :  (80, 128)
descriptor shape  2900  :  (82, 128)
descriptor shape  2901  :  (386, 128)
descriptor shape  2902  :  (81, 128)
descriptor shape  2903  :  (136, 128)
descriptor shape  2904  :  (381, 128)
descriptor shape  2905  :  (78, 128)
descriptor shape  2906  :  (197, 128)
descriptor shape  2907  :  (95, 128)
descriptor shape  2908  :  (188, 128)
descriptor shape  2909  :  (409, 128)
descriptor shape  2910  :  (153, 128)
descriptor shape  2911  :  (164, 128)
descriptor shape  2912  :  (248, 128)
descriptor shape  2913  :  (98, 128)
descriptor shape  2914  :  (76, 128)
descriptor shape  2915  :  (131, 128)
descriptor shape  2916  :  (151, 128)
descriptor shape  2917  :  (129, 128)
descriptor shape  2918  :  (129, 128)
descriptor shape  2919  :  (503, 128)
descriptor shape  2920  :  (128, 128)
descriptor shape  2921  :  (117, 128)
descriptor shape  2922  :  (116, 128)
descriptor shape  29

descriptor shape  3115  :  (38, 128)
descriptor shape  3116  :  (163, 128)
descriptor shape  3117  :  (225, 128)
descriptor shape  3118  :  (172, 128)
descriptor shape  3119  :  (83, 128)
descriptor shape  3120  :  (302, 128)
descriptor shape  3121  :  (174, 128)
descriptor shape  3122  :  (35, 128)
descriptor shape  3123  :  (115, 128)
descriptor shape  3124  :  (440, 128)
descriptor shape  3125  :  (93, 128)
descriptor shape  3126  :  (150, 128)
descriptor shape  3127  :  (75, 128)
descriptor shape  3128  :  (185, 128)
descriptor shape  3129  :  (145, 128)
descriptor shape  3130  :  (162, 128)
descriptor shape  3131  :  (192, 128)
descriptor shape  3132  :  (370, 128)
descriptor shape  3133  :  (184, 128)
descriptor shape  3134  :  (311, 128)
descriptor shape  3135  :  (93, 128)
descriptor shape  3136  :  (117, 128)
descriptor shape  3137  :  (93, 128)
descriptor shape  3138  :  (197, 128)
descriptor shape  3139  :  (123, 128)
descriptor shape  3140  :  (335, 128)
descriptor shape  3

descriptor shape  3342  :  (264, 128)
descriptor shape  3343  :  (122, 128)
descriptor shape  3344  :  (44, 128)
descriptor shape  3345  :  (255, 128)
descriptor shape  3346  :  (169, 128)
descriptor shape  3347  :  (170, 128)
descriptor shape  3348  :  (72, 128)
descriptor shape  3349  :  (187, 128)
descriptor shape  3350  :  (108, 128)
descriptor shape  3351  :  (184, 128)
descriptor shape  3352  :  (84, 128)
descriptor shape  3353  :  (97, 128)
descriptor shape  3354  :  (258, 128)
descriptor shape  3355  :  (488, 128)
descriptor shape  3356  :  (177, 128)
descriptor shape  3357  :  (192, 128)
descriptor shape  3358  :  (289, 128)
descriptor shape  3359  :  (198, 128)


In [4]:
i=0
for filename in os.listdir(folder2):
    #path
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('Positive_Down.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (108, 128)
descriptor shape  1  :  (13, 128)
descriptor shape  2  :  (67, 128)
descriptor shape  3  :  (401, 128)
descriptor shape  4  :  (148, 128)
descriptor shape  5  :  (164, 128)
descriptor shape  6  :  (228, 128)
descriptor shape  7  :  (120, 128)
descriptor shape  8  :  (144, 128)
descriptor shape  9  :  (428, 128)
descriptor shape  10  :  (221, 128)
descriptor shape  11  :  (153, 128)
descriptor shape  12  :  (274, 128)
descriptor shape  13  :  (187, 128)
descriptor shape  14  :  (94, 128)
descriptor shape  15  :  (277, 128)
descriptor shape  16  :  (169, 128)
descriptor shape  17  :  (163, 128)
descriptor shape  18  :  (94, 128)
descriptor shape  19  :  (88, 128)
descriptor shape  20  :  (213, 128)
descriptor shape  21  :  (174, 128)
descriptor shape  22  :  (130, 128)
descriptor shape  23  :  (99, 128)
descriptor shape  24  :  (191, 128)
descriptor shape  25  :  (517, 128)
descriptor shape  26  :  (364, 128)
descriptor shape  27  :  (130, 128)
descript

descriptor shape  226  :  (178, 128)
descriptor shape  227  :  (180, 128)
descriptor shape  228  :  (77, 128)
descriptor shape  229  :  (194, 128)
descriptor shape  230  :  (90, 128)
descriptor shape  231  :  (435, 128)
descriptor shape  232  :  (295, 128)
descriptor shape  233  :  (113, 128)
descriptor shape  234  :  (130, 128)
descriptor shape  235  :  (133, 128)
descriptor shape  236  :  (59, 128)
descriptor shape  237  :  (277, 128)
descriptor shape  238  :  (54, 128)
descriptor shape  239  :  (158, 128)
descriptor shape  240  :  (287, 128)
descriptor shape  241  :  (184, 128)
descriptor shape  242  :  (178, 128)
descriptor shape  243  :  (72, 128)
descriptor shape  244  :  (831, 128)
descriptor shape  245  :  (113, 128)
descriptor shape  246  :  (135, 128)
descriptor shape  247  :  (73, 128)
descriptor shape  248  :  (248, 128)
descriptor shape  249  :  (96, 128)
descriptor shape  250  :  (147, 128)
descriptor shape  251  :  (113, 128)
descriptor shape  252  :  (233, 128)
descript

descriptor shape  454  :  (591, 128)
descriptor shape  455  :  (116, 128)
descriptor shape  456  :  (196, 128)
descriptor shape  457  :  (191, 128)
descriptor shape  458  :  (111, 128)
descriptor shape  459  :  (54, 128)
descriptor shape  460  :  (125, 128)
descriptor shape  461  :  (556, 128)
descriptor shape  462  :  (250, 128)
descriptor shape  463  :  (54, 128)
descriptor shape  464  :  (428, 128)
descriptor shape  465  :  (48, 128)
descriptor shape  466  :  (451, 128)
descriptor shape  467  :  (457, 128)
descriptor shape  468  :  (456, 128)
descriptor shape  469  :  (169, 128)
descriptor shape  470  :  (449, 128)
descriptor shape  471  :  (128, 128)
descriptor shape  472  :  (513, 128)
descriptor shape  473  :  (59, 128)
descriptor shape  474  :  (114, 128)
descriptor shape  475  :  (170, 128)
descriptor shape  476  :  (13, 128)
descriptor shape  477  :  (196, 128)
descriptor shape  478  :  (128, 128)
descriptor shape  479  :  (46, 128)
descriptor shape  480  :  (253, 128)
descrip

descriptor shape  678  :  (85, 128)
descriptor shape  679  :  (93, 128)
descriptor shape  680  :  (29, 128)
descriptor shape  681  :  (184, 128)
descriptor shape  682  :  (89, 128)
descriptor shape  683  :  (202, 128)
descriptor shape  684  :  (110, 128)
descriptor shape  685  :  (46, 128)
descriptor shape  686  :  (586, 128)
descriptor shape  687  :  (52, 128)
descriptor shape  688  :  (258, 128)
descriptor shape  689  :  (311, 128)
descriptor shape  690  :  (583, 128)
descriptor shape  691  :  (453, 128)
descriptor shape  692  :  (397, 128)
descriptor shape  693  :  (60, 128)
descriptor shape  694  :  (296, 128)
descriptor shape  695  :  (202, 128)
descriptor shape  696  :  (142, 128)
descriptor shape  697  :  (431, 128)
descriptor shape  698  :  (228, 128)
descriptor shape  699  :  (178, 128)
descriptor shape  700  :  (422, 128)
descriptor shape  701  :  (140, 128)
descriptor shape  702  :  (271, 128)
descriptor shape  703  :  (274, 128)
descriptor shape  704  :  (89, 128)
descripto

descriptor shape  902  :  (156, 128)
descriptor shape  903  :  (82, 128)
descriptor shape  904  :  (30, 128)
descriptor shape  905  :  (241, 128)
descriptor shape  906  :  (178, 128)
descriptor shape  907  :  (474, 128)
descriptor shape  908  :  (29, 128)
descriptor shape  909  :  (574, 128)
descriptor shape  910  :  (84, 128)
descriptor shape  911  :  (488, 128)
descriptor shape  912  :  (233, 128)
descriptor shape  913  :  (180, 128)
descriptor shape  914  :  (508, 128)
descriptor shape  915  :  (435, 128)
descriptor shape  916  :  (274, 128)
descriptor shape  917  :  (101, 128)
descriptor shape  918  :  (577, 128)
descriptor shape  919  :  (445, 128)
descriptor shape  920  :  (48, 128)
descriptor shape  921  :  (27, 128)
descriptor shape  922  :  (84, 128)
descriptor shape  923  :  (84, 128)
descriptor shape  924  :  (237, 128)
descriptor shape  925  :  (673, 128)
descriptor shape  926  :  (166, 128)
descriptor shape  927  :  (747, 128)
descriptor shape  928  :  (255, 128)
descripto

descriptor shape  1123  :  (432, 128)
descriptor shape  1124  :  (140, 128)
descriptor shape  1125  :  (168, 128)
descriptor shape  1126  :  (107, 128)
descriptor shape  1127  :  (214, 128)
descriptor shape  1128  :  (144, 128)
descriptor shape  1129  :  (445, 128)
descriptor shape  1130  :  (319, 128)
descriptor shape  1131  :  (130, 128)
descriptor shape  1132  :  (343, 128)
descriptor shape  1133  :  (423, 128)
descriptor shape  1134  :  (101, 128)
descriptor shape  1135  :  (432, 128)
descriptor shape  1136  :  (67, 128)
descriptor shape  1137  :  (193, 128)
descriptor shape  1138  :  (174, 128)
descriptor shape  1139  :  (133, 128)
descriptor shape  1140  :  (357, 128)
descriptor shape  1141  :  (488, 128)
descriptor shape  1142  :  (91, 128)
descriptor shape  1143  :  (224, 128)
descriptor shape  1144  :  (429, 128)
descriptor shape  1145  :  (320, 128)
descriptor shape  1146  :  (398, 128)
descriptor shape  1147  :  (133, 128)
descriptor shape  1148  :  (30, 128)
descriptor shap

descriptor shape  1344  :  (432, 128)
descriptor shape  1345  :  (216, 128)
descriptor shape  1346  :  (236, 128)
descriptor shape  1347  :  (145, 128)
descriptor shape  1348  :  (214, 128)
descriptor shape  1349  :  (108, 128)
descriptor shape  1350  :  (302, 128)
descriptor shape  1351  :  (587, 128)
descriptor shape  1352  :  (250, 128)
descriptor shape  1353  :  (162, 128)
descriptor shape  1354  :  (274, 128)
descriptor shape  1355  :  (465, 128)
descriptor shape  1356  :  (456, 128)
descriptor shape  1357  :  (151, 128)
descriptor shape  1358  :  (152, 128)
descriptor shape  1359  :  (86, 128)
descriptor shape  1360  :  (319, 128)
descriptor shape  1361  :  (60, 128)
descriptor shape  1362  :  (113, 128)
descriptor shape  1363  :  (423, 128)
descriptor shape  1364  :  (456, 128)
descriptor shape  1365  :  (150, 128)
descriptor shape  1366  :  (333, 128)
descriptor shape  1367  :  (101, 128)
descriptor shape  1368  :  (269, 128)
descriptor shape  1369  :  (232, 128)
descriptor sha

descriptor shape  1568  :  (170, 128)
descriptor shape  1569  :  (235, 128)
descriptor shape  1570  :  (100, 128)
descriptor shape  1571  :  (525, 128)
descriptor shape  1572  :  (333, 128)
descriptor shape  1573  :  (168, 128)
descriptor shape  1574  :  (317, 128)
descriptor shape  1575  :  (143, 128)
descriptor shape  1576  :  (125, 128)
descriptor shape  1577  :  (160, 128)
descriptor shape  1578  :  (241, 128)
descriptor shape  1579  :  (64, 128)
descriptor shape  1580  :  (333, 128)
descriptor shape  1581  :  (277, 128)
descriptor shape  1582  :  (248, 128)
descriptor shape  1583  :  (100, 128)
descriptor shape  1584  :  (324, 128)
descriptor shape  1585  :  (177, 128)
descriptor shape  1586  :  (337, 128)
descriptor shape  1587  :  (484, 128)
descriptor shape  1588  :  (176, 128)
descriptor shape  1589  :  (221, 128)
descriptor shape  1590  :  (216, 128)
descriptor shape  1591  :  (86, 128)
descriptor shape  1592  :  (462, 128)
descriptor shape  1593  :  (195, 128)
descriptor sha

descriptor shape  1787  :  (107, 128)
descriptor shape  1788  :  (448, 128)
descriptor shape  1789  :  (48, 128)
descriptor shape  1790  :  (432, 128)
descriptor shape  1791  :  (163, 128)
descriptor shape  1792  :  (172, 128)
descriptor shape  1793  :  (497, 128)
descriptor shape  1794  :  (76, 128)
descriptor shape  1795  :  (298, 128)
descriptor shape  1796  :  (9, 128)
descriptor shape  1797  :  (203, 128)
descriptor shape  1798  :  (70, 128)
descriptor shape  1799  :  (172, 128)
descriptor shape  1800  :  (169, 128)
descriptor shape  1801  :  (65, 128)
descriptor shape  1802  :  (590, 128)
descriptor shape  1803  :  (167, 128)
descriptor shape  1804  :  (102, 128)
descriptor shape  1805  :  (63, 128)
descriptor shape  1806  :  (127, 128)
descriptor shape  1807  :  (240, 128)
descriptor shape  1808  :  (110, 128)
descriptor shape  1809  :  (220, 128)
descriptor shape  1810  :  (107, 128)
descriptor shape  1811  :  (123, 128)
descriptor shape  1812  :  (119, 128)
descriptor shape  1

descriptor shape  2004  :  (87, 128)
descriptor shape  2005  :  (27, 128)
descriptor shape  2006  :  (152, 128)
descriptor shape  2007  :  (90, 128)
descriptor shape  2008  :  (588, 128)
descriptor shape  2009  :  (159, 128)
descriptor shape  2010  :  (456, 128)
descriptor shape  2011  :  (85, 128)
descriptor shape  2012  :  (147, 128)
descriptor shape  2013  :  (8, 128)
descriptor shape  2014  :  (13, 128)
descriptor shape  2015  :  (79, 128)
descriptor shape  2016  :  (557, 128)
descriptor shape  2017  :  (131, 128)
descriptor shape  2018  :  (250, 128)
descriptor shape  2019  :  (463, 128)
descriptor shape  2020  :  (162, 128)
descriptor shape  2021  :  (277, 128)
descriptor shape  2022  :  (203, 128)
descriptor shape  2023  :  (133, 128)
descriptor shape  2024  :  (831, 128)
descriptor shape  2025  :  (48, 128)
descriptor shape  2026  :  (53, 128)
descriptor shape  2027  :  (108, 128)
descriptor shape  2028  :  (282, 128)
descriptor shape  2029  :  (242, 128)
descriptor shape  2030

descriptor shape  2225  :  (100, 128)
descriptor shape  2226  :  (100, 128)
descriptor shape  2227  :  (49, 128)
descriptor shape  2228  :  (216, 128)
descriptor shape  2229  :  (470, 128)
descriptor shape  2230  :  (76, 128)
descriptor shape  2231  :  (162, 128)
descriptor shape  2232  :  (397, 128)
descriptor shape  2233  :  (141, 128)
descriptor shape  2234  :  (103, 128)
descriptor shape  2235  :  (317, 128)
descriptor shape  2236  :  (227, 128)
descriptor shape  2237  :  (54, 128)
descriptor shape  2238  :  (99, 128)
descriptor shape  2239  :  (432, 128)
descriptor shape  2240  :  (417, 128)
descriptor shape  2241  :  (142, 128)
descriptor shape  2242  :  (196, 128)
descriptor shape  2243  :  (414, 128)
descriptor shape  2244  :  (497, 128)
descriptor shape  2245  :  (9, 128)
descriptor shape  2246  :  (84, 128)
descriptor shape  2247  :  (84, 128)
descriptor shape  2248  :  (194, 128)
descriptor shape  2249  :  (334, 128)
descriptor shape  2250  :  (265, 128)
descriptor shape  22

descriptor shape  2445  :  (214, 128)
descriptor shape  2446  :  (114, 128)
descriptor shape  2447  :  (157, 128)
descriptor shape  2448  :  (488, 128)
descriptor shape  2449  :  (146, 128)
descriptor shape  2450  :  (191, 128)
descriptor shape  2451  :  (284, 128)
descriptor shape  2452  :  (132, 128)
descriptor shape  2453  :  (258, 128)
descriptor shape  2454  :  (85, 128)
descriptor shape  2455  :  (493, 128)
descriptor shape  2456  :  (333, 128)
descriptor shape  2457  :  (152, 128)
descriptor shape  2458  :  (117, 128)
descriptor shape  2459  :  (97, 128)
descriptor shape  2460  :  (168, 128)
descriptor shape  2461  :  (117, 128)
descriptor shape  2462  :  (593, 128)
descriptor shape  2463  :  (561, 128)
descriptor shape  2464  :  (398, 128)
descriptor shape  2465  :  (229, 128)
descriptor shape  2466  :  (79, 128)
descriptor shape  2467  :  (459, 128)
descriptor shape  2468  :  (166, 128)
descriptor shape  2469  :  (77, 128)
descriptor shape  2470  :  (345, 128)
descriptor shape

descriptor shape  2665  :  (207, 128)
descriptor shape  2666  :  (555, 128)
descriptor shape  2667  :  (248, 128)
descriptor shape  2668  :  (105, 128)
descriptor shape  2669  :  (164, 128)
descriptor shape  2670  :  (13, 128)
descriptor shape  2671  :  (170, 128)
descriptor shape  2672  :  (117, 128)
descriptor shape  2673  :  (521, 128)
descriptor shape  2674  :  (93, 128)
descriptor shape  2675  :  (148, 128)
descriptor shape  2676  :  (574, 128)
descriptor shape  2677  :  (164, 128)
descriptor shape  2678  :  (68, 128)
descriptor shape  2679  :  (108, 128)
descriptor shape  2680  :  (410, 128)
descriptor shape  2681  :  (151, 128)
descriptor shape  2682  :  (67, 128)
descriptor shape  2683  :  (102, 128)
descriptor shape  2684  :  (555, 128)
descriptor shape  2685  :  (59, 128)
descriptor shape  2686  :  (401, 128)
descriptor shape  2687  :  (163, 128)
descriptor shape  2688  :  (753, 128)
descriptor shape  2689  :  (321, 128)
descriptor shape  2690  :  (96, 128)
descriptor shape  

descriptor shape  2887  :  (108, 128)
descriptor shape  2888  :  (175, 128)
descriptor shape  2889  :  (652, 128)
descriptor shape  2890  :  (333, 128)
descriptor shape  2891  :  (323, 128)
descriptor shape  2892  :  (133, 128)
descriptor shape  2893  :  (422, 128)
descriptor shape  2894  :  (244, 128)
descriptor shape  2895  :  (422, 128)
descriptor shape  2896  :  (410, 128)
descriptor shape  2897  :  (105, 128)
descriptor shape  2898  :  (277, 128)
descriptor shape  2899  :  (424, 128)
descriptor shape  2900  :  (476, 128)
descriptor shape  2901  :  (265, 128)
descriptor shape  2902  :  (79, 128)
descriptor shape  2903  :  (320, 128)
descriptor shape  2904  :  (224, 128)
descriptor shape  2905  :  (153, 128)
descriptor shape  2906  :  (153, 128)
descriptor shape  2907  :  (493, 128)
descriptor shape  2908  :  (88, 128)
descriptor shape  2909  :  (316, 128)
descriptor shape  2910  :  (173, 128)
descriptor shape  2911  :  (65, 128)
descriptor shape  2912  :  (429, 128)
descriptor shap

In [2]:
data1 = pd.read_csv(r'Positive_Up.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         2    1    0    0    0    0    1    1  136    2  ...    0    2  143   
1         1    0    0    0    0    0    8   13  130    1  ...    1   11  159   
2         8    9    0    0    0    0    0    1   33   30  ...    0    2   97   
3        12    9    1    0    0    0    0    1   25   26  ...    0    4   81   
4         9  139    9    0    1    3    6   10    1  139  ...    0    0    2   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
619951    0    0    0   12   91    9    0    0   50   43  ...   11   10   55   
619952   10   19    0    0    0    6   59   10  147  125  ...   12  111   53   
619953    0    1  147   64    3    0    0    0    2    9  ...    0   10   17   
619954    0    0    0    0    0    0    0    0    1    4  ...   32   87   41   
619955    2   27   70   27    7    0    0    0   38    8  ...    3   15   37   

        121  122  123  124  125  126  127  
0         5    0    0   46    4    0    1  
1         6    0    0    8    6    1    4  
2        33    0    0   13   20    6   10  
3        25    0    0   43   23    1    2  
4       139  111    0    0    1    2    0  
...     ...  ...  ...  ...  ...  ...  ...  
619951   26    0    0    0    0    0    1  
619952    9    0    0    0    0    1    8  
619953    1    1    3   49   67    0    3  
619954    6   17   38   42    8    0    4  
619955    4    0    0    0    0    0    1  

[619956 rows x 128 columns]

In [3]:
data2 = pd.read_csv(r'Positive_Down.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data2=data2.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data2

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    0   89   52   15   32    8    0   76   75  ...    0    1   22   
1         0    4   13    1    0    0    0    0   73  109  ...    1   27    3   
2        30    0    0    0    8  127   41   33  112    6  ...   15   26    5   
3         0    0   22   36   18   39   10    4   60    6  ...    1   36   68   
4         0    2   71   13    2    8    2    0    1    3  ...  122    5    0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
689086    1    1    0    0    0    0    0    0  100   47  ...    2   12    0   
689087   45   67    8    1    2    2    4   13   21   19  ...  114   46   10   
689088   55   53   37    0    0    0    3   17   56   75  ...    3   11   21   
689089    0    0    0    0    0    0    0    0    4    1  ...    1    2   25   
689090    0    0    0    0    0    0    0    0   48   24  ...    4   69   25   

        121  122  123  124  125  126  127  
0         2    0    1    7    0    0    0  
1         0    0    2    1    1   17   49  
2         3    3    2    2    0    0    1  
3         7    0    0    0    0    0    5  
4        18   39    0    0   39   35    0  
...     ...  ...  ...  ...  ...  ...  ...  
689086    0    1   31   20   11    5    0  
689087    0    0    0   23   85   71   35  
689088   32    0    0    0    0    0    0  
689089    5    3    7   17    4    0    5  
689090    3    1   13    9    4    3    7  

[689091 rows x 128 columns]

In [7]:
i=0
for filename in os.listdir(folder3):
    
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('Negative.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (638, 128)
descriptor shape  1  :  (306, 128)
descriptor shape  2  :  (411, 128)
descriptor shape  3  :  (592, 128)
descriptor shape  4  :  (272, 128)
descriptor shape  5  :  (176, 128)
descriptor shape  6  :  (474, 128)
descriptor shape  7  :  (339, 128)
descriptor shape  8  :  (602, 128)
descriptor shape  9  :  (368, 128)
descriptor shape  10  :  (717, 128)
descriptor shape  11  :  (131, 128)
descriptor shape  12  :  (524, 128)
descriptor shape  13  :  (228, 128)
descriptor shape  14  :  (303, 128)
descriptor shape  15  :  (385, 128)
descriptor shape  16  :  (389, 128)
descriptor shape  17  :  (307, 128)
descriptor shape  18  :  (489, 128)
descriptor shape  19  :  (332, 128)
descriptor shape  20  :  (211, 128)
descriptor shape  21  :  (100, 128)
descriptor shape  22  :  (398, 128)
descriptor shape  23  :  (630, 128)
descriptor shape  24  :  (5, 128)
descriptor shape  25  :  (766, 128)
descriptor shape  26  :  (506, 128)
descriptor shape  27  :  (248, 128)
desc

descriptor shape  226  :  (282, 128)
descriptor shape  227  :  (1209, 128)
descriptor shape  228  :  (47, 128)
descriptor shape  229  :  (307, 128)
descriptor shape  230  :  (701, 128)
descriptor shape  231  :  (445, 128)
descriptor shape  232  :  (273, 128)
descriptor shape  233  :  (227, 128)
descriptor shape  234  :  (906, 128)
descriptor shape  235  :  (300, 128)
descriptor shape  236  :  (450, 128)
descriptor shape  237  :  (521, 128)
descriptor shape  238  :  (348, 128)
descriptor shape  239  :  (354, 128)
descriptor shape  240  :  (404, 128)
descriptor shape  241  :  (384, 128)
descriptor shape  242  :  (613, 128)
descriptor shape  243  :  (442, 128)
descriptor shape  244  :  (164, 128)
descriptor shape  245  :  (557, 128)
descriptor shape  246  :  (353, 128)
descriptor shape  247  :  (276, 128)
descriptor shape  248  :  (314, 128)
descriptor shape  249  :  (96, 128)
descriptor shape  250  :  (616, 128)
descriptor shape  251  :  (883, 128)
descriptor shape  252  :  (348, 128)
de

descriptor shape  452  :  (550, 128)
descriptor shape  453  :  (190, 128)
descriptor shape  454  :  (474, 128)
descriptor shape  455  :  (192, 128)
descriptor shape  456  :  (408, 128)
descriptor shape  457  :  (342, 128)
descriptor shape  458  :  (551, 128)
descriptor shape  459  :  (167, 128)
descriptor shape  460  :  (888, 128)
descriptor shape  461  :  (538, 128)
descriptor shape  462  :  (277, 128)
descriptor shape  463  :  (1109, 128)
descriptor shape  464  :  (461, 128)
descriptor shape  465  :  (574, 128)
descriptor shape  466  :  (633, 128)
descriptor shape  467  :  (693, 128)
descriptor shape  468  :  (190, 128)
descriptor shape  469  :  (62, 128)
descriptor shape  470  :  (427, 128)
descriptor shape  471  :  (337, 128)
descriptor shape  472  :  (326, 128)
descriptor shape  473  :  (160, 128)
descriptor shape  474  :  (319, 128)
descriptor shape  475  :  (184, 128)
descriptor shape  476  :  (33, 128)
descriptor shape  477  :  (78, 128)
descriptor shape  478  :  (417, 128)
des

descriptor shape  678  :  (216, 128)
descriptor shape  679  :  (345, 128)
descriptor shape  680  :  (251, 128)
descriptor shape  681  :  (320, 128)
descriptor shape  682  :  (243, 128)
descriptor shape  683  :  (270, 128)
descriptor shape  684  :  (239, 128)
descriptor shape  685  :  (383, 128)
descriptor shape  686  :  (386, 128)
descriptor shape  687  :  (296, 128)
descriptor shape  688  :  (491, 128)
descriptor shape  689  :  (134, 128)
descriptor shape  690  :  (391, 128)
descriptor shape  691  :  (500, 128)
descriptor shape  692  :  (151, 128)
descriptor shape  693  :  (320, 128)
descriptor shape  694  :  (735, 128)
descriptor shape  695  :  (123, 128)
descriptor shape  696  :  (574, 128)
descriptor shape  697  :  (201, 128)
descriptor shape  698  :  (604, 128)
descriptor shape  699  :  (809, 128)
descriptor shape  700  :  (217, 128)
descriptor shape  701  :  (366, 128)
descriptor shape  702  :  (364, 128)
descriptor shape  703  :  (517, 128)
descriptor shape  704  :  (201, 128)
d

descriptor shape  905  :  (142, 128)
descriptor shape  906  :  (184, 128)
descriptor shape  907  :  (318, 128)
descriptor shape  908  :  (185, 128)
descriptor shape  909  :  (219, 128)
descriptor shape  910  :  (134, 128)
descriptor shape  911  :  (337, 128)
descriptor shape  912  :  (392, 128)
descriptor shape  913  :  (144, 128)
descriptor shape  914  :  (455, 128)
descriptor shape  915  :  (97, 128)
descriptor shape  916  :  (939, 128)
descriptor shape  917  :  (315, 128)
descriptor shape  918  :  (304, 128)
descriptor shape  919  :  (541, 128)
descriptor shape  920  :  (139, 128)
descriptor shape  921  :  (551, 128)
descriptor shape  922  :  (117, 128)
descriptor shape  923  :  (285, 128)
descriptor shape  924  :  (78, 128)
descriptor shape  925  :  (536, 128)
descriptor shape  926  :  (282, 128)
descriptor shape  927  :  (166, 128)
descriptor shape  928  :  (278, 128)
descriptor shape  929  :  (85, 128)
descriptor shape  930  :  (332, 128)
descriptor shape  931  :  (131, 128)
desc

descriptor shape  1124  :  (219, 128)
descriptor shape  1125  :  (204, 128)
descriptor shape  1126  :  (428, 128)
descriptor shape  1127  :  (681, 128)
descriptor shape  1128  :  (120, 128)
descriptor shape  1129  :  (197, 128)
descriptor shape  1130  :  (790, 128)
descriptor shape  1131  :  (477, 128)
descriptor shape  1132  :  (215, 128)
descriptor shape  1133  :  (168, 128)
descriptor shape  1134  :  (620, 128)
descriptor shape  1135  :  (144, 128)
descriptor shape  1136  :  (413, 128)
descriptor shape  1137  :  (765, 128)
descriptor shape  1138  :  (441, 128)
descriptor shape  1139  :  (313, 128)
descriptor shape  1140  :  (313, 128)
descriptor shape  1141  :  (278, 128)
descriptor shape  1142  :  (36, 128)
descriptor shape  1143  :  (393, 128)
descriptor shape  1144  :  (922, 128)
descriptor shape  1145  :  (63, 128)
descriptor shape  1146  :  (247, 128)
descriptor shape  1147  :  (600, 128)
descriptor shape  1148  :  (403, 128)
descriptor shape  1149  :  (508, 128)
descriptor sha

descriptor shape  1345  :  (266, 128)
descriptor shape  1346  :  (334, 128)
descriptor shape  1347  :  (265, 128)
descriptor shape  1348  :  (684, 128)
descriptor shape  1349  :  (40, 128)
descriptor shape  1350  :  (656, 128)
descriptor shape  1351  :  (678, 128)
descriptor shape  1352  :  (97, 128)
descriptor shape  1353  :  (336, 128)
descriptor shape  1354  :  (109, 128)
descriptor shape  1355  :  (447, 128)
descriptor shape  1356  :  (189, 128)
descriptor shape  1357  :  (106, 128)
descriptor shape  1358  :  (337, 128)
descriptor shape  1359  :  (413, 128)
descriptor shape  1360  :  (426, 128)
descriptor shape  1361  :  (204, 128)
descriptor shape  1362  :  (204, 128)
descriptor shape  1363  :  (198, 128)
descriptor shape  1364  :  (722, 128)
descriptor shape  1365  :  (143, 128)
descriptor shape  1366  :  (71, 128)
descriptor shape  1367  :  (334, 128)
descriptor shape  1368  :  (117, 128)
descriptor shape  1369  :  (354, 128)
descriptor shape  1370  :  (232, 128)
descriptor shap

descriptor shape  1564  :  (621, 128)
descriptor shape  1565  :  (159, 128)
descriptor shape  1566  :  (48, 128)
descriptor shape  1567  :  (689, 128)
descriptor shape  1568  :  (162, 128)
descriptor shape  1569  :  (468, 128)
descriptor shape  1570  :  (266, 128)
descriptor shape  1571  :  (121, 128)
descriptor shape  1572  :  (784, 128)
descriptor shape  1573  :  (91, 128)
descriptor shape  1574  :  (403, 128)
descriptor shape  1575  :  (445, 128)
descriptor shape  1576  :  (361, 128)
descriptor shape  1577  :  (487, 128)
descriptor shape  1578  :  (336, 128)
descriptor shape  1579  :  (218, 128)
descriptor shape  1580  :  (140, 128)
descriptor shape  1581  :  (375, 128)
descriptor shape  1582  :  (267, 128)
descriptor shape  1583  :  (281, 128)
descriptor shape  1584  :  (556, 128)
descriptor shape  1585  :  (311, 128)
descriptor shape  1586  :  (366, 128)
descriptor shape  1587  :  (491, 128)
descriptor shape  1588  :  (517, 128)
descriptor shape  1589  :  (197, 128)
descriptor sha

descriptor shape  1781  :  (671, 128)
descriptor shape  1782  :  (216, 128)
descriptor shape  1783  :  (186, 128)
descriptor shape  1784  :  (408, 128)
descriptor shape  1785  :  (533, 128)
descriptor shape  1786  :  (142, 128)
descriptor shape  1787  :  (222, 128)
descriptor shape  1788  :  (559, 128)
descriptor shape  1789  :  (507, 128)
descriptor shape  1790  :  (114, 128)
descriptor shape  1791  :  (277, 128)
descriptor shape  1792  :  (449, 128)
descriptor shape  1793  :  (438, 128)
descriptor shape  1794  :  (177, 128)
descriptor shape  1795  :  (642, 128)
descriptor shape  1796  :  (390, 128)
descriptor shape  1797  :  (205, 128)
descriptor shape  1798  :  (537, 128)
descriptor shape  1799  :  (167, 128)
descriptor shape  1800  :  (253, 128)
descriptor shape  1801  :  (221, 128)
descriptor shape  1802  :  (48, 128)
descriptor shape  1803  :  (557, 128)
descriptor shape  1804  :  (752, 128)
descriptor shape  1805  :  (217, 128)
descriptor shape  1806  :  (33, 128)
descriptor sha

descriptor shape  2000  :  (98, 128)
descriptor shape  2001  :  (567, 128)
descriptor shape  2002  :  (460, 128)
descriptor shape  2003  :  (450, 128)
descriptor shape  2004  :  (146, 128)
descriptor shape  2005  :  (195, 128)
descriptor shape  2006  :  (174, 128)
descriptor shape  2007  :  (521, 128)
descriptor shape  2008  :  (480, 128)
descriptor shape  2009  :  (370, 128)
descriptor shape  2010  :  (350, 128)
descriptor shape  2011  :  (199, 128)
descriptor shape  2012  :  (380, 128)
descriptor shape  2013  :  (500, 128)
descriptor shape  2014  :  (80, 128)
descriptor shape  2015  :  (105, 128)
descriptor shape  2016  :  (782, 128)
descriptor shape  2017  :  (15, 128)
descriptor shape  2018  :  (142, 128)
descriptor shape  2019  :  (801, 128)
descriptor shape  2020  :  (464, 128)
descriptor shape  2021  :  (273, 128)
descriptor shape  2022  :  (225, 128)
descriptor shape  2023  :  (346, 128)
descriptor shape  2024  :  (396, 128)
descriptor shape  2025  :  (430, 128)
descriptor shap

descriptor shape  2217  :  (249, 128)
descriptor shape  2218  :  (411, 128)
descriptor shape  2219  :  (141, 128)
descriptor shape  2220  :  (334, 128)
descriptor shape  2221  :  (252, 128)
descriptor shape  2222  :  (64, 128)
descriptor shape  2223  :  (355, 128)
descriptor shape  2224  :  (337, 128)
descriptor shape  2225  :  (253, 128)
descriptor shape  2226  :  (358, 128)
descriptor shape  2227  :  (533, 128)
descriptor shape  2228  :  (373, 128)
descriptor shape  2229  :  (469, 128)
descriptor shape  2230  :  (208, 128)
descriptor shape  2231  :  (327, 128)
descriptor shape  2232  :  (183, 128)
descriptor shape  2233  :  (184, 128)
descriptor shape  2234  :  (373, 128)
descriptor shape  2235  :  (617, 128)
descriptor shape  2236  :  (143, 128)
descriptor shape  2237  :  (225, 128)
descriptor shape  2238  :  (143, 128)
descriptor shape  2239  :  (293, 128)
descriptor shape  2240  :  (331, 128)
descriptor shape  2241  :  (428, 128)
descriptor shape  2242  :  (273, 128)
descriptor sh

descriptor shape  2437  :  (111, 128)
descriptor shape  2438  :  (255, 128)
descriptor shape  2439  :  (157, 128)
descriptor shape  2440  :  (93, 128)
descriptor shape  2441  :  (247, 128)
descriptor shape  2442  :  (230, 128)
descriptor shape  2443  :  (84, 128)
descriptor shape  2444  :  (139, 128)
descriptor shape  2445  :  (593, 128)
descriptor shape  2446  :  (393, 128)
descriptor shape  2447  :  (129, 128)
descriptor shape  2448  :  (254, 128)
descriptor shape  2449  :  (141, 128)
descriptor shape  2450  :  (130, 128)
descriptor shape  2451  :  (542, 128)
descriptor shape  2452  :  (279, 128)
descriptor shape  2453  :  (757, 128)
descriptor shape  2454  :  (421, 128)
descriptor shape  2455  :  (106, 128)
descriptor shape  2456  :  (194, 128)
descriptor shape  2457  :  (416, 128)
descriptor shape  2458  :  (459, 128)
descriptor shape  2459  :  (344, 128)
descriptor shape  2460  :  (280, 128)
descriptor shape  2461  :  (118, 128)
descriptor shape  2462  :  (180, 128)
descriptor sha

descriptor shape  2656  :  (110, 128)
descriptor shape  2657  :  (229, 128)


In [4]:
data3= pd.read_csv(r'Negative.csv',header=None,dtype='uint8')
data3=data3.astype(np.uint8)
data3

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    0    0    0    0    0    0    0    3    6  ...   56   81   99   
1        34    2    7   11    0    0    6  119   26   40  ...    8   32   72   
2         5    8    1    2    1    3    6    4    8    9  ...    2   18   13   
3        54   11   35   24    0    0    5   73   44   44  ...    9    0    0   
4        38   17    1    0    0    0    3    9   51   24  ...   18   22    9   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
918456   10    1    0    0    0    2   37  136   28    2  ...    4   24   33   
918457    2    2    0    0    0    0    0    0   16    9  ...    3   27   31   
918458   34   28   10   22   55    6    0    3  102   40  ...   15    5    0   
918459   18   45   63   28   10    0    0    0  136  135  ...    0    1   17   
918460   13    0    0    0    0    0    1   32   16    0  ...    0    0    0   

        121  122  123  124  125  126  127  
0        25    5   33   37   28    1   20  
1         1    6   12    9   16  104  119  
2         7   18   66   40   13    8    8  
3         4   18   11    4   11    1    0  
4        14    6    6    8   25   55   35  
...     ...  ...  ...  ...  ...  ...  ...  
918456   44   53   79   18    0    0    1  
918457    1    1    8    3    1   21   69  
918458    0    1    2    1    1    0    0  
918459   11   11    0    0    0    0    2  
918460   34  119   76   21    0    0    0  

[918461 rows x 128 columns]

In [5]:
data=data1.append(data2)

In [6]:
data = data.append(data3)

In [11]:
csv_data=data.to_csv('Sift_Final.csv', mode='a', header=False,index=False)

In [7]:
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         2    1    0    0    0    0    1    1  136    2  ...    0    2  143   
1         1    0    0    0    0    0    8   13  130    1  ...    1   11  159   
2         8    9    0    0    0    0    0    1   33   30  ...    0    2   97   
3        12    9    1    0    0    0    0    1   25   26  ...    0    4   81   
4         9  139    9    0    1    3    6   10    1  139  ...    0    0    2   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
918456   10    1    0    0    0    2   37  136   28    2  ...    4   24   33   
918457    2    2    0    0    0    0    0    0   16    9  ...    3   27   31   
918458   34   28   10   22   55    6    0    3  102   40  ...   15    5    0   
918459   18   45   63   28   10    0    0    0  136  135  ...    0    1   17   
918460   13    0    0    0    0    0    1   32   16    0  ...    0    0    0   

        121  122  123  124  125  126  127  
0         5    0    0   46    4    0    1  
1         6    0    0    8    6    1    4  
2        33    0    0   13   20    6   10  
3        25    0    0   43   23    1    2  
4       139  111    0    0    1    2    0  
...     ...  ...  ...  ...  ...  ...  ...  
918456   44   53   79   18    0    0    1  
918457    1    1    8    3    1   21   69  
918458    0    1    2    1    1    0    0  
918459   11   11    0    0    0    0    2  
918460   34  119   76   21    0    0    0  

[2227508 rows x 128 columns]

# Kmeans

In [8]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(data)

KMeans(n_clusters=5)

In [9]:
import pickle

In [37]:
# save the model to disk
filename = 'Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [10]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([538261, 341162, 573521, 433228, 341336], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [141]:
#folder1=r"D:/StrData/Str"
#folder2=r"D:\StrData\Nstr"

In [40]:
#performing kmeans prediction of the UP Staircase dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('FinalUpStr.csv', mode='a',header=False,index=False)

In [41]:
#performing kmeans prediction of the Down Staircase dataset with the pretrained kmeans model

#initialising i=1; as its the second class
i=1
data=[]
#k=0

for filename in os.listdir(folder2):
    #path
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('FinalDownStr.csv', mode='a',header=False,index=False)

In [42]:
#performing kmeans prediction of the entire Non_Staircase dataset with the pretrained kmeans model

#initialising i=2, as its the 3rd class
i=2
data=[]
k=0
for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
#     print(path)
    resize=(200,200)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        continue
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('FinalNegativeStr.csv', mode='a',header=False,index=False)

In [11]:
#Displaying the kmeans predicted data
print("Up Staircase")
dat1= pd.read_csv(r'FinalUpStr.csv',header=None)
print(dat1)

Up Staircase
       0   1    2    3    4  5
0     58  19   22    5   17  0
1     24  58   55   33   23  0
2     29  23   16   37   14  0
3     36   5    5   15    5  0
4     25  65   59   33   25  0
...   ..  ..  ...  ...  ... ..
3355  53  92  104  128  111  0
3356  45  29   44   32   27  0
3357  58  29   45   30   30  0
3358  65  46   64   61   53  0
3359  68  42   34   19   35  0

[3360 rows x 6 columns]


In [12]:
#Displaying the kmeans predicted data
print("Down Staircase")
dat2= pd.read_csv(r'FinalDownStr.csv',header=None)
print(dat2)

Down Staircase
       0   1    2    3    4  5
0     16  30   17   24   21  1
1     10   0    0    3    0  1
2     33   5   11   12    6  1
3     56  95  127   62   61  1
4     40  14   16   19   59  1
...   ..  ..  ...  ...  ... ..
3004  40  12    4   20   21  1
3005  13   9   14   10   20  1
3006  36  96   77   46   47  1
3007  82  57   72   41   44  1
3008  62  64   67  122  153  1

[3009 rows x 6 columns]


In [13]:
print("Non-Staircase")
dat3= pd.read_csv(r'FinalNegativeStr.csv',header=None)
print(dat3)

Non-Staircase
       0    1    2   3   4  5
0     49  259  266  42  22  2
1     47   67   66  77  49  2
2     71  133  134  30  43  2
3     58  199  193  76  66  2
4     44   92   81  33  22  2
...   ..  ...  ...  ..  .. ..
2652   8    9   13  10   1  2
2653  69  106  110  70  58  2
2654  59  281  335  87  74  2
2655  53   21   27   3   6  2
2656  16   96   57  31  29  2

[2657 rows x 6 columns]


In [14]:
#appending All classes into 1 csv file

A=dat1.append(dat2)
A = A.append(dat3)


In [ ]:
csv_data=A.to_csv('FinalFV.csv', mode='a',header=False,index=False)

In [15]:
A

0    1    2   3   4  5
0     58   19   22   5  17  0
1     24   58   55  33  23  0
2     29   23   16  37  14  0
3     36    5    5  15   5  0
4     25   65   59  33  25  0
...   ..  ...  ...  ..  .. ..
2652   8    9   13  10   1  2
2653  69  106  110  70  58  2
2654  59  281  335  87  74  2
2655  53   21   27   3   6  2
2656  16   96   57  31  29  2

[9026 rows x 6 columns]

In [16]:
x = A.iloc[:,0:5].values

In [17]:
x

array([[ 58,  19,  22,   5,  17],
       [ 24,  58,  55,  33,  23],
       [ 29,  23,  16,  37,  14],
       ...,
       [ 59, 281, 335,  87,  74],
       [ 53,  21,  27,   3,   6],
       [ 16,  96,  57,  31,  29]], dtype=int64)

In [18]:
y = A.iloc[:,5].values

In [19]:
y

array([0, 0, 0, ..., 2, 2, 2], dtype=int64)

In [20]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [21]:
Dhoni

array([[ 0.40189271, -0.6780679 , -0.64605736, -1.0869782 , -0.69769655],
       [-0.96894692, -0.02673859, -0.13221389, -0.15922729, -0.49699937],
       [-0.76735286, -0.61126489, -0.73948345, -0.02669145, -0.79804514],
       ...,
       [ 0.44221152,  3.69752896,  4.22767016,  1.63000659,  1.20892661],
       [ 0.20029864, -0.6446664 , -0.56820229, -1.15324612, -1.06564137],
       [-1.29149743,  0.60788996, -0.10107186, -0.22549522, -0.2963022 ]])

In [22]:
from sklearn.decomposition import PCA

In [23]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [24]:
Bhumi = pca.transform(Dhoni)

In [25]:
Bhumi

array([[-1.32738368e+00, -4.05887686e-01, -8.33049053e-01,
         2.93806117e-01, -1.00688720e-03],
       [-6.98574565e-01, -1.37496375e-01,  8.05284186e-01,
        -2.66607659e-01, -5.42344402e-02],
       [-1.28590674e+00,  2.82776599e-01,  3.08167775e-01,
        -5.64202169e-01, -9.44489850e-03],
       ...,
       [ 5.28828335e+00, -2.14976196e+00,  1.74798899e+00,
        -2.46559665e-01,  3.93975912e-01],
       [-1.53911028e+00, -6.58904507e-01, -6.55625894e-01,
         8.58675023e-02,  6.24671856e-02],
       [-4.20999439e-01, -3.23331834e-01,  1.26939426e+00,
        -1.60703257e-01, -5.17090976e-01]])

In [26]:
Bhumi = pd.DataFrame(Bhumi)

In [27]:
Bhumi

0         1         2         3         4
0    -1.327384 -0.405888 -0.833049  0.293806 -0.001007
1    -0.698575 -0.137496  0.805284 -0.266608 -0.054234
2    -1.285907  0.282777  0.308168 -0.564202 -0.009445
3    -1.894060 -0.090207 -0.143495 -0.239283  0.043604
4    -0.567745 -0.189164  0.816369 -0.226110 -0.100042
...        ...       ...       ...       ...       ...
9021 -2.312911 -0.171373  0.932459 -0.234659  0.052539
9022  1.805246  0.120883 -0.290225 -0.270755  0.019637
9023  5.288283 -2.149762  1.747989 -0.246560  0.393976
9024 -1.539110 -0.658905 -0.655626  0.085868  0.062467
9025 -0.420999 -0.323332  1.269394 -0.160703 -0.517091

[9026 rows x 5 columns]

In [28]:
Bhumi.shape

(9026, 5)

In [29]:
print(pca.explained_variance_ratio_) 

[0.64269117 0.16666847 0.14502456 0.03393209 0.0116837 ]


In [30]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [65]:
# save the model to disk
filename = 'PCA_3_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [31]:
Bhumi = pca.transform(Dhoni)

In [32]:
Bhumi

array([[-1.32738368, -0.40588769, -0.83304905],
       [-0.69857456, -0.13749638,  0.80528419],
       [-1.28590674,  0.2827766 ,  0.30816777],
       ...,
       [ 5.28828335, -2.14976196,  1.74798899],
       [-1.53911028, -0.65890451, -0.65562589],
       [-0.42099944, -0.32333183,  1.26939426]])

In [33]:
Bhumi.shape

(9026, 3)

In [34]:
print(pca.explained_variance_ratio_) 

[0.64269117 0.16666847 0.14502456]


In [35]:
Bhumi = pd.DataFrame(Bhumi)

In [36]:
Bhumi

0         1         2
0    -1.327384 -0.405888 -0.833049
1    -0.698575 -0.137496  0.805284
2    -1.285907  0.282777  0.308168
3    -1.894060 -0.090207 -0.143495
4    -0.567745 -0.189164  0.816369
...        ...       ...       ...
9021 -2.312911 -0.171373  0.932459
9022  1.805246  0.120883 -0.290225
9023  5.288283 -2.149762  1.747989
9024 -1.539110 -0.658905 -0.655626
9025 -0.420999 -0.323332  1.269394

[9026 rows x 3 columns]

In [37]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [38]:
B

0         1         2  0
0    -1.327384 -0.405888 -0.833049  0
1    -0.698575 -0.137496  0.805284  0
2    -1.285907  0.282777  0.308168  0
3    -1.894060 -0.090207 -0.143495  0
4    -0.567745 -0.189164  0.816369  0
...        ...       ...       ... ..
9021 -2.312911 -0.171373  0.932459  2
9022  1.805246  0.120883 -0.290225  2
9023  5.288283 -2.149762  1.747989  2
9024 -1.539110 -0.658905 -0.655626  2
9025 -0.420999 -0.323332  1.269394  2

[9026 rows x 4 columns]

In [75]:
csv_data=B.to_csv('FinalPCAFV.csv', mode='a',header=False,index=False)

# Training ,Testing & Classification

In [39]:
data= pd.read_csv(r'FinalPCAFV.csv',header=None)

data

0         1         2  3
0    -1.327384 -0.405888 -0.833049  0
1    -0.698575 -0.137496  0.805284  0
2    -1.285907  0.282777  0.308168  0
3    -1.894060 -0.090207 -0.143495  0
4    -0.567745 -0.189164  0.816369  0
...        ...       ...       ... ..
9021 -2.312911 -0.171373  0.932459  2
9022  1.805246  0.120883 -0.290225  2
9023  5.288283 -2.149762  1.747989  2
9024 -1.539110 -0.658905 -0.655626  2
9025 -0.420999 -0.323332  1.269394  2

[9026 rows x 4 columns]

In [40]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[-1.32738368 -0.40588769 -0.83304905]
 [-0.69857456 -0.13749638  0.80528419]
 [-1.28590674  0.2827766   0.30816777]
 ...
 [ 5.28828335 -2.14976196  1.74798899]
 [-1.53911028 -0.65890451 -0.65562589]
 [-0.42099944 -0.32333183  1.26939426]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
9021    2
9022    2
9023    2
9024    2
9025    2
Name: 3, Length: 9026, dtype: int64


In [41]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

## Decision Tree


In [81]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

Decision Tree Results
Decision Tree Accuracy:  76.91029900332225 %


In [82]:
print("Decision Tree")
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred1))
print("Confusion Matrix :")
print(metrics.confusion_matrix(y_test, y_pred1))
print("Classification Report")
print(classification_report(y_test, y_pred1))

Decision Tree
Testing Accuracy: 0.7691029900332226
Confusion Matrix :
[[596  59  13]
 [164 425   8]
 [108  65 368]]
Classification Report
              precision    recall  f1-score   support

           0       0.69      0.89      0.78       668
           1       0.77      0.71      0.74       597
           2       0.95      0.68      0.79       541

    accuracy                           0.77      1806
   macro avg       0.80      0.76      0.77      1806
weighted avg       0.79      0.77      0.77      1806



In [44]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"Final Negative Dataset\9090.jpg"


#Repeated the process of image pre-processing and feature extraction
a=cv2.imread(path)
resize=(200,200)

#resize image
img=cv2.resize(a,resize)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#initialise sift descriptor
sift = cv2.xfeatures2d.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(gray, None)

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (740, 128)
Histogram:
      0   1    2   3   4
0  263  64  281  55  77


In [45]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [46]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [47]:
Mukta.shape

(1, 5)

In [48]:
MB = pca.transform(Mukta)

In [49]:
MB.shape

(1, 3)

In [50]:
MB

array([[-4.58966622e-17, -5.10853714e-18, -2.16593506e-17]])

In [51]:
#prediction
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[0]


## Support vector classifiers

RBF (Radial Basis function)

In [84]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [85]:
y_pred_LK = Dhoni_LK.predict(x_test)
accuracy_score(y_test, y_pred_LK)# accuracy for rbf function

0.5714285714285714

In [86]:
print("SVC RBF")
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred_LK))
print("Confusion Matrix :")
print(metrics.confusion_matrix(y_test, y_pred_LK))
print("Classification Report")
print(classification_report(y_test, y_pred_LK))

SVC RBF
Testing Accuracy: 0.5714285714285714
Confusion Matrix :
[[548  64  56]
 [387 145  65]
 [142  60 339]]
Classification Report
              precision    recall  f1-score   support

           0       0.51      0.82      0.63       668
           1       0.54      0.24      0.33       597
           2       0.74      0.63      0.68       541

    accuracy                           0.57      1806
   macro avg       0.59      0.56      0.55      1806
weighted avg       0.59      0.57      0.55      1806



In [125]:
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [54]:
Dhoni_LK

SVC()

Linear

In [55]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='linear')#linear function
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [56]:
y_pred_LK = Dhoni_LK.predict(x_test)
accuracy_score(y_test, y_pred_LK) #accuracy for linear function

0.5243632336655593

Poly

In [87]:
from sklearn.svm import SVC  
DhoniSVM_LK = SVC(kernel='poly')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [88]:
y_pred_LK = Dhoni_LK.predict(x_test)
accuracy_score(y_test, y_pred_LK)#accuracy for poly

0.4568106312292359

In [89]:
print("SVC RBF")
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred_LK))
print("Confusion Matrix :")
print(metrics.confusion_matrix(y_test, y_pred_LK))
print("Classification Report")
print(classification_report(y_test, y_pred_LK))

SVC RBF
Testing Accuracy: 0.4568106312292359
Confusion Matrix :
[[638  18  12]
 [521  47  29]
 [362  39 140]]
Classification Report
              precision    recall  f1-score   support

           0       0.42      0.96      0.58       668
           1       0.45      0.08      0.13       597
           2       0.77      0.26      0.39       541

    accuracy                           0.46      1806
   macro avg       0.55      0.43      0.37      1806
weighted avg       0.54      0.46      0.38      1806



In [59]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [60]:
y_pred_LK

array([0, 1, 0, ..., 2, 2, 0], dtype=int64)

In [61]:
from sklearn.metrics import confusion_matrix

In [62]:
confusion_matrix(y_test, y_pred_LK)

array([[638,  18,  12],
       [521,  47,  29],
       [362,  39, 140]], dtype=int64)

In [63]:
from sklearn.metrics import accuracy_score

In [64]:
accuracy_score(y_test, y_pred_LK)

0.4568106312292359

In [65]:
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[0]


## KNN

In [77]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train )
ypred = model.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, ypred ))

Accuracy: 0.8189368770764119


In [80]:
print("KNN")
print("Testing Accuracy:",metrics.accuracy_score(y_test, ypred))
print("Confusion Matrix :")
print(metrics.confusion_matrix(y_test, ypred))
print("Classification Report")
print(classification_report(y_test, ypred))

KNN
Testing Accuracy: 0.8189368770764119
Confusion Matrix :
[[587  50  31]
 [ 36 557   4]
 [109  97 335]]
Classification Report
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       668
           1       0.79      0.93      0.86       597
           2       0.91      0.62      0.74       541

    accuracy                           0.82      1806
   macro avg       0.83      0.81      0.81      1806
weighted avg       0.83      0.82      0.81      1806



## Random Forest

In [68]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)
y_pred_train=clf.predict(x_train)
y_pred=clf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.9352159468438538


In [70]:
# print("Training Accuracy:",metrics.accuracy_score(y_train, y_pred))
print("Training Accuracy:",metrics.accuracy_score(y_train, y_pred_train))
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred))
cm1 = metrics.confusion_matrix(y_test, y_pred)
print("Confusion matrix:",metrics.confusion_matrix(y_test, y_pred))
print('Precision: %.3f' % metrics.precision_score(y_test, y_pred,average = "micro"))
print('Recall: %.3f' % metrics.recall_score(y_test, y_pred, average = "micro"))
print('F1 Score: %.3f' % metrics.f1_score(y_test, y_pred, average = "micro"))

Training Accuracy: 1.0
Testing Accuracy: 0.9352159468438538
Confusion matrix: [[668   0   0]
 [  2 588   7]
 [ 70  38 433]]
Precision: 0.935
Recall: 0.935
F1 Score: 0.935


In [71]:
FP = cm1.sum(axis=0) - np.diag(cm1)
FN = cm1.sum(axis=1) - np.diag(cm1)
TP = np.diag(cm1)
TN = cm1.sum() - (FP + FN + TP)
FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)
# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Sensitivity : ", TPR)
# Specificity or true negative rate
TNR = TN/(TN+FP)
print("Specificity : ",TNR)

Sensitivity :  [1.         0.98492462 0.80036969]
Specificity :  [0.93673111 0.96856907 0.9944664 ]


In [76]:
print("Random Forest")
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix :")
print(cm1)
print("Classification Report")
print(classification_report(y_test, y_pred))

Random Forest
Testing Accuracy: 0.9352159468438538
Confusion Matrix :
[[668   0   0]
 [  2 588   7]
 [ 70  38 433]]
Classification Report
              precision    recall  f1-score   support

           0       0.90      1.00      0.95       668
           1       0.94      0.98      0.96       597
           2       0.98      0.80      0.88       541

    accuracy                           0.94      1806
   macro avg       0.94      0.93      0.93      1806
weighted avg       0.94      0.94      0.93      1806

